### PR TITLE
WIP: Multi-line logs + standardized output

### PR DESCRIPTION
**Pull request by dmwilcox**
Hello, nice project!

I added some stuff to make the logs more detailed and handle stack traces and multi-line logs gracefully.  It does semi-depend on a PR I have with the author of fuzzytime -- at least if you want milliseconds in the output timestamp fields.

https://github.com/bcampbell/fuzzytime/pull/4

I also added support for using the task-group shared 'Service' if a task does not have it's own (former introduced in Nomad 0.10.0-beta1 for use with shared network namespaces).

### CODE REVIEW

**Comment by adragoset** [comment]
Hi, thanks for the contribution. It will take me a a few days to go through this and I'll probably wait for nomad 0.10 to release before cutting a new release version but I will incorporate your changes and test them out on my cluster.

**Comment by sas1024** [comment]
Hello! @adragoset any news with this PR ?

**Comment by adragoset** [comment]
Hi i merged your pr.

**Comment by dmwilcox** [comment]
Thank you!  I'll see about trying some test cases on a new Nomad version to send along a README PR.

I used to use nomad_follower as a system job which aggregated all of the jobs logs (including it's own) and it worked like a dream.  There is a potential data loss gap (which I'll try and remember and will flag to you) but it's small.

**Comment by adragoset** [comment]
Hey its no problem im going to check out all this stuff you added. I just stood up loki for our nomad cluster and im going to setup promtail to read from the nomad_follower log so i should get a chance to thoroughly test everything. Theres a few options but id like to get this app working well with the loki grafana promtail stack.

**Pull request merged**
